In [ ]:
# calculates the mutual information from a confusion matrix

In [1]:
import numpy as np
import time
import json

In [2]:
num_classes = 6

In [3]:
# import json
file = open('labels.txt', 'r')
true_labels_list = []
myline = file.readline()
mylist = myline.split()
true_labels_list.append(mylist)
while myline:
    myline = file.readline()
    mylist = myline.split()
    true_labels_list.append(mylist)
# data = json.load(file)
file.close()

In [4]:
predicted_labels_as_ints = np.array([0]*(len(true_labels_list) -1))
true_labels_as_ints = np.array([0]*(len(true_labels_list) -1))

In [5]:
file2 = open('predictions.json', 'r')
predicted_data = json.load(file2)
file2.close()

In [6]:
for i in range(len(true_labels_list) - 1):

    true_labels_as_ints[i] = int(true_labels_list[i][0])
    predicted_labels_as_ints[i] = predicted_data[str(i)]['class'][0]# TODO

num_correct = 0
for i in range(len(predicted_labels_as_ints)):
    if predicted_labels_as_ints[i] == true_labels_as_ints[i]:
        num_correct += 1

print(num_correct/len(predicted_labels_as_ints))

0.7833333333333333


In [7]:
confusion_matrix = np.array([[0]*num_classes]*num_classes)

In [8]:
for i in range(len(predicted_labels_as_ints)):
    # column = actual class
    # row = predicted class
    column = true_labels_as_ints[i]
    row = predicted_labels_as_ints[i]
    confusion_matrix[row][column] += 1

In [9]:
# normalize confusion matrix without using explicit for loop
tic = time.time()
column_sums2 = confusion_matrix.sum(axis=0)
print(column_sums2)
norm_confusion_matrix = confusion_matrix/column_sums2
print(norm_confusion_matrix)
toc = time.time()
print(toc-tic)

[40 40 40 40 40 40]
[[1.    0.    0.    0.    0.    0.   ]
 [0.    1.    0.175 0.    0.    0.   ]
 [0.    0.    0.6   0.125 0.    0.   ]
 [0.    0.    0.225 0.625 0.15  0.   ]
 [0.    0.    0.    0.25  0.65  0.175]
 [0.    0.    0.    0.    0.2   0.825]]
0.0008189678192138672


In [10]:
rows, cols = norm_confusion_matrix.shape

In [11]:
n_classes = 6
p_true = 1.0 / n_classes  # uniform prior

# Joint probability: p(i,j) = P(pred=i | true=j) * P(true=j)
p_i_j = norm_confusion_matrix * p_true

# Marginals
p_i = p_i_j.sum(axis=1)  # P(predicted class)
p_j = p_i_j.sum(axis=0)  # P(true class) - should all be 1/6

# Mutual information
my_sum = 0.0
for i in range(n_classes):
    for j in range(n_classes):
        if p_i_j[i,j] != 0.0:
            my_sum += p_i_j[i,j] * np.log2(p_i_j[i,j] / (p_i[i] * p_j[j]))

print(my_sum)  

1.8018241348566464
